dist: trusty
sudo: false
language: cpp
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
script: export CC=gcc-4.9 CXX=g++-4.9; make -C ui/linux && make -C tests && cd tests && ./test_all
