dist: trusty
sudo: false
language: cpp
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libgtest-dev
script: export CC=gcc-5 CXX=g++-5; make -C ui/linux && make -C tests && cd tests && ./test_all
